### ISSUE TITLE
Add More Drupal Vulnerability Scanner

### ISSUE THREAD

**Issue by lukstah4** [Anon6372098/FazScan#1]
I'm excited on your FazScan program/tool. I suggest you to add more options on Drupal Vulnerability Scanner. Such like Drupal **avatar-afd** and etc.

**Comment by mfazrinizar** [comment]
Nice idea !. ASAP i'll do it.

**Comment by mfazrinizar** [comment]
I've done one addition and i will close this issue. If you have any idea with a detail vulnerability information, just open new issue and use the new issue template. Thank you ! :)
