### ISSUE TITLE
I can't Install LWP::UserAgent

### ISSUE THREAD

**Issue by kirakira07** [Anon6372098/FazScan#2]
I'm using Termux to install FazScan. I'm facing this error, i've tried to use cpan install LWP::UserAgent, but it displayed new errors. I've followed your procedures, please help !

**Comment by antahbelantah** [comment]
use sudo ?

**Comment by mfazrinizar** [comment]
@kirakira07 What OS are you using to run FazScan ? Android, yeah. Check out the readme display, there is a complete installation guide. I guess that you haven't installed among clang or make package(s).

**Comment by mfazrinizar** [comment]
@kirakira07 Use command

cpan install -fi LWP::UserAgent.

It will fix the problem.
