### ISSUE TITLE
Request New Feature

### ISSUE THREAD

**Issue by jenguy01** [Anon6372098/FazScan#4]
**Is your feature request related to a problem? Please describe.**
No. Yeah, a little. For some newbie(s) it's a little confused to install

**Describe the solution you'd like**
Adding more feature(s) with good quality and a clear instruction(s)

**Describe alternatives you've considered**
More responsive display of the program and some loops

**Additional context**
How about if you're planning to add a feature about Web Information Gathering. It will be very nice !. I'll contribute by share this program to my social media. Great program sir !

**Comment by mfazrinizar** [comment]
![soon](https://user-images.githubusercontent.com/43740735/55299187-0474d200-545c-11e9-812b-681fc62ec1e2.png)

I'm working on it ! :)

**Comment by mfazrinizar** [comment]
Okay, i've done it. I've just released the v1.2 with 2 new feature options. Take a look :)
